name: "Auto Release adder"
on:
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  auto-release-adder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The PR
        uses: actions/checkout@v4

      - name: Get Release Version
        id: get_release_version
        run: |
          text="${{ steps.create_release_body.outputs.release_body }}"
          regex="v([0-9]+)\.([0-9]+)\.([0-9]+)"
          if [[ "$text" =~ $regex ]]; then
            echo "version=${BASH_REMATCH[0]}" >> "$GITHUB_OUTPUT"
          fi

      - name: Add Release 
        run: |
          tag="v1.0.0"
          title="$tag"
          body="${{ github.event.pull_request.body }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{
              \"tag_name\": \"$tag\",
              \"target_commitish\": \"production\",
              \"name\": \"$title\",
              \"body\": \"$body\",
              \"draft\": false,
              \"prerelease\": false,
              \"generate_release_notes\": false
            }"