name: "Auto Release adder"
on:
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  auto-release-adder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The PR
        uses: actions/checkout@v4

      - name: Create Release Body
        id: create_release_body
        run: kotlinc -script .github/scripts/auto_release_adder.kts "${{ github.event.pull_request.body }}"

      - name: Add Release 
        run: |
          tag="${{ steps.create_release_body.outputs.release_version }}"
          title="$TAG"
          bodyData="${{ steps.create_release_body.outputs.release_body }}"
          body=$(echo "$bodyData" | sed 's/|#@/\n/g')
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{
              \"tag_name\": \"$tag\",
              \"target_commitish\": \"production\",
              \"name\": \"$title\",
              \"body\": \"$body\",
              \"draft\": false,
              \"prerelease\": false,
              \"generate_release_notes\": false
            }"