name: "Release Drafter"
on:
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the pr
        uses: actions/checkout@v4

      - name: Create Release Draft
        run: |
          # GitHub API를 사용하여 Release Draft 생성
          curl -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "tag_name": "v${{ github.event.pull_request.number }}",  # PR 번호를 태그로 사용
              "name": "${{ github.event.pull_request.title }}",  # PR 제목
              "body": "${{ github.event.pull_request.body }}",  # PR 본문
              "draft": true,
              "prerelease": false,
              "target_commitish": "production"  # production 브랜치
            }'