name: "Release Drafter"
on:
  pull_request:
    types: [closed]
    branches:
      - production
jobs:
  release-drafter:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout the pr
        uses: actions/checkout@v4

      - name: Create Release Draft
        run: |
          # GitHub API를 사용하여 Release Draft 생성
          curl -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
	      "tag_name": "'"tag"'",
              "name": "'"title"'",
              "body": "'"body"'",
              "draft": true,
              "prerelease": false,
              "target_commitish": "'"main"'"
            }'
